INSERT INTO ACCOUNT (ACCOUNT_NO, NAME, POLICY_TYPE, BALANCE)
VALUES (1001, 'Shanil', 'Savings', 50000);

INSERT INTO ACCOUNT (ACCOUNT_NO, NAME, POLICY_TYPE, BALANCE)
VALUES (1002, 'FundMe User', 'Loan', 250000);
